# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  rustbuild:
    steps:
      - checkout
      - run: sudo apt-get update 
      - run: sudo apt-get install libdbus-1-dev libsystemd-dev pkg-config libdbus-1-3 libssl-dev
      - run: cargo build --verbose 
      - run: cargo test --verbose 

executors:
  docker-executor:
    docker:
      - image: cimg/rust:1.51.0

jobs:
  build: 
    executor: docker-executor
    steps:
      - rustbuild