# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  foo:
    steps:
      - run: which java

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk

jobs:
  build: 
    executor: docker-executor
    steps:
      - foo