name: Centos8-Nightly

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: centos8
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ~/.cargo/bin/cargo build --verbose --release
      - name: Run tests
        run: cargo test --verbose
      - name: Create RPM scaffolding
        run: |
          cp -r rpm target/
          cp target/release/agent target/rpm/SOURCES
          tar czvf target/rpm/SOURCES/stackable-agent-0.1.0.tar.gz target/rpm/SOURCES/stackable-agent-0.1.0
      - name: Build RPM
        run: /usr/bin/rpmbuild --define "_topdir ``/target/rpm" -v -ba target/SPECS/stackable-agent-0.1.0.spec