name: simple rust build

on: [push, pull_request]

jobs:
  build_and_test:
    name: stackable agent
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --release
          override: true
      - uses: actions/upload-artifact@v2
        with:
          path: ./target/release/agent
          if-no-files-found: error

#- name: Nexus Repo Publish
#    uses: sonatype-nexus-community/nexus-repo-github-action@master
#    with:
#      serverUrl: https://nexus.stackable.tech/
#      username: github
#      password: ${{ secrets.password }}
#      format: maven2
#      repository: maven-releases
#      coordinates: groupId=com.example artifactId=app version=1.0.0
#      assets: extension=jar
#     filename: ./target/release